/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : IRRx.c
**     Project     : Controlador_AGV
**     Processor   : MC9S08QE128CLK
**     Component   : Capture
**     Version     : Component 02.223, Driver 01.30, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2016-03-29, 10:56, # CodeGen: 39
**     Abstract    :
**         This component "Capture" simply implements the capture function
**         of timer. The counter counts the same way as in free run mode. On
**         the selected edge of the input signal (on the input pin), the current
**         content of the counter register is written into the capture
**         register and the OnCapture event is called.
**     Settings    :
**             Timer capture encapsulation : Capture
**
**         Timer
**             Timer                   : TPM2
**             Counter shared          : Yes
**
**         High speed mode
**             Prescaler               : divide-by-64
**           Maximal time for capture register
**             Xtal ticks              : 5461
**             microseconds            : 166667
**             milliseconds            : 167
**             seconds (real)          : 0.166666666667
**             Hz                      : 6
**           One tick of timer is
**             microseconds            : 2.543132
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Capture                : TPM2C0V   [$0056]
**              Counter                : TPM2CNT   [$0051]
**              Mode                   : TPM2SC    [$0050]
**              Run                    : TPM2SC    [$0050]
**              Prescaler              : TPM2SC    [$0050]
**
**         Used input pin              : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       61            |  PTA1_KBI1P1_TPM2CH0_ADP1_ACMP1MINUS
**             ----------------------------------------------------
**
**         Port name                   : PTA
**         Bit number (in port)        : 1
**         Bit mask of the port        : $0002
**
**         Signal edge/level           : both
**         Priority                    : 
**         Pull option                 : off
**
**     Contents    :
**         EnableEvent     - byte IRRx_EnableEvent(void);
**         DisableEvent    - byte IRRx_DisableEvent(void);
**         Reset           - byte IRRx_Reset(void);
**         GetCaptureValue - byte IRRx_GetCaptureValue(IRRx_TCapturedValue *Value);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file IRRx.c
** @version 01.30
** @brief
**         This component "Capture" simply implements the capture function
**         of timer. The counter counts the same way as in free run mode. On
**         the selected edge of the input signal (on the input pin), the current
**         content of the counter register is written into the capture
**         register and the OnCapture event is called.
*/         
/*!
**  @addtogroup IRRx_module IRRx module documentation
**  @{
*/         

/* MODULE IRRx. */

#include "Events.h"
#include "IRRx.h"


volatile bool IRRx_EnEvent;            /* Enable/Disable events */
volatile word IRRx_CntrState;          /* Content of counter */


/*
** ===================================================================
**     Method      :  IRRx_EnableEvent (component Capture)
**     Description :
**         This method enables the events. This method is available
**         only if any event is selected.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte IRRx_EnableEvent(void)

**  This method is implemented as a macro. See IRRx.h file.  **
*/

/*
** ===================================================================
**     Method      :  IRRx_DisableEvent (component Capture)
**     Description :
**         This method disables the events.  This method is available
**         only if any event is selected.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte IRRx_DisableEvent(void)

**  This method is implemented as a macro. See IRRx.h file.  **
*/

/*
** ===================================================================
**     Method      :  IRRx_Reset (component Capture)
**     Description :
**         This method resets the counter register (see implementation
**         note in <General Info>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte IRRx_Reset(word *Value)

**  This method is implemented as a macro. See IRRx.h file.  **
*/

/*
** ===================================================================
**     Method      :  IRRx_GetCaptureValue (component Capture)
**     Description :
**         This method gets the last value captured by enabled timer.
**         Note: one tick of timer is
**               2.543132 us in high speed mode
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the content of the
**                           capture register
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte IRRx_GetCaptureValue(IRRx_TCapturedValue *Value)

**  This method is implemented as a macro. See IRRx.h file.  **
*/

/*
** ===================================================================
**     Method      :  IRRx_Init (component Capture)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IRRx_Init(void)
{
  /* TPM2C0V: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(TPM2C0V, 0x00U);            /* Clear capture register */ 
  IRRx_CntrState = 0x00U;              /* Clear variable */
  IRRx_EnEvent = TRUE;                 /* Enable events */
  /* TPM2C0SC: CH0F=0,CH0IE=1,MS0B=0,MS0A=0,ELS0B=1,ELS0A=1,??=0,??=0 */
  setReg8(TPM2C0SC, 0x4CU);            /* Enable both interrupt and capture function */ 
}


/*
** ===================================================================
**     Method      :  Interrupt (component Capture)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(IRRx_Interrupt)
{
  (void)TPM2C0SC;                      /* Dummy read to reset interrupt request flag */
  /* TPM2C0SC: CH0F=0 */
  clrReg8Bits(TPM2C0SC, 0x80U);        /* Reset interrupt request flag */ 
  if (IRRx_EnEvent) {                  /* Are the events enabled? */
    IRRx_OnCapture();                  /* Invoke user event */
  }
}



/* END IRRx. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
